title: Timbral Technique
description: A demo site for a double-blind submission
remote_theme: pages-themes/cayman@v0.2.0

plugins:
  - jekyll-remote-theme

# Jekyll will look for these include overrides:
defaults:
  -
    scope:
      path: ""
    values:
      head: head-custom
