title: Timbral Technique
description: A project website for vocal timbre technique conversion
remote_theme: pages-themes/cayman@v0.2.0

plugins:
  - jekyll-remote-theme

# Add this:
include:
  - assets/css/custom.css
