remote_theme: pages-themes/cayman@v0.2.0

plugins:
  - jekyll-remote-theme

# Inject head-custom.html and override default includes
defaults:
  -
    scope:
      path: ""
    values:
      head: head-custom

